### ISSUE TITLE
Please cut github releases with pre-compiled versions

### ISSUE THREAD

**Issue by drnic** [soutenniza/nats#3]
1. Create pre-compiled versions for osx, linux32, linux64 (say using https://github.com/mitchellh/gox)
2. Cut github releases (say using https://github.com/aktau/github-release)

Example of using github-release:
- https://github.com/cloudfoundry-community/traveling-cf-admin/blob/master/Rakefile#L41-L44
- https://github.com/cloudfoundry-community/traveling-cf-admin/blob/master/Rakefile#L58-L60

**Comment by drnic** [comment]
Required for https://github.com/cloudfoundry-community/traveling-cf-admin/issues/2

**Comment by soutenniza** [comment]
Release 1.0.0 cut

**Comment by drnic** [comment]
Lovely!
